ENT.Type = "anim"
ENT.Base = "durgz_base"
ENT.PrintName = "Aspirin"
ENT.Nicknames = {0}
ENT.OverdosePhrase = {0}
ENT.Author = "cheesylard (inspired by ninjers)"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Information	 = "Gets rid of headaches" 
